# Generated by Django 3.2.9 on 2022-01-10 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0010_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='neighbourhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='neighbourhood.neighbourhood'),
        ),
    ]
