# Generated by Django 3.2.9 on 2022-01-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0014_alter_neighbourhood_hood_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='help_line',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
