# Generated by Django 3.2.9 on 2022-01-11 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0015_neighbourhood_help_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.neighbourhood'),
        ),
    ]
